Use minitest that doesn't break auto_trace tests
Unconfirmed but I believe this fix from 5.10.2 is the cause of our
issue:

> Fixed location of nil assert_equal deprecation to work with
> expectations. (jeremyevans)

The error is: `NoMethodError: undefined method `assert_equal' for nil:NilClass`