07 regression tests in ci (#11)
* fix cassandra config file path

#7

* comment out 1.8.7 and jruby from versions to be tested

#7

* use mysql gem only with ruby < 2.4

!not sure about the implications of this!

the mysql gem has not been updated since 2013 and "doesn't like the unification of integer types" https://stackoverflow.com/a/41521197/2120436

#7

* oops, correct files for previous commit

#7

* add swig install and rake fetch_ext_deps

- these are prerequisits for oboe to compile

#7

* split up the multiline command copied from Dockerfile

#7

* fix curl command so that it writes to a file and not STDOUT

#7

* add append flag to tee command

-otherwise the mapping of localhost gets overwritten

#7

* fix the tar command

#7

* lets read and write the fetched files in binary mode to get past this occasional conversion problem in travis ...

Encoding::UndefinedConversionError: "\xD3" from ASCII-8BIT to UTF-8

#7

* remove parallel execution of tests (hopefully for real now)

- comment out `require minitest/hell`
- remove parallelize_me!

they are basically the same:
https://github.com/seattlerb/minitest/blob/master/lib/minitest/hell.rb

#7

* set N=1 to further avoid parallel execution

even though after commenting out `require minitest/hell` the number of 
- failures went down from 83 to 52
- errors went down from 42 to 20

https://github.com/librato/ruby-tracelytics/issues/3
https://chriskottom.com/blog/2014/10/exploring-minitest-concurrency/

#7

* only run mysql tests for ruby versions < 2.4

- the mysql gem doesn't install for 2.4 and higher because of the unified integers
- the mysql gem has not been developed since 2014, has no maintainer and only 13% of the tests pass, there is no point in trying to fix it, because mysql2 should be used instead.

#7

* use an older version of cassandra

#7

* fix cassandra install command line

#7

* revert to using current cassandra version

#7

* exclude cassandra tests for now

- they need refactoring to use the 'cassandra-driver' gem
- instead of the 'cassandra' gem, which hasn't had a commit since 09/2014
- we also need to check what we are instrumenting for cassandra

#7

* remove puts

#7

* change it up, because of this error in travis:

NoMethodError: undefined method `test_files` for #<Rake::TestTask:0x00000002c17058>

#7

* try another approach with the t.test_files

#7

* skip tests properly with the skip method

#7

* revert previous commit

it would have been nice to skip all the tests this way, but
unfortunately it doesn't seem to work

#7

* Updated to only treat v2 xtrace as valid

* add error code which has been missing in the message

looks like this got fixed in the mongo gem

#7

* this may now work again without :query and not throw an error

got:
@selector={:findAndModify=>"users", :query=>{}, :new=>true, :update=>{:query=>{"$inc"=>{:likes=>1}}}}
          @fields=nil>
        failed with error 52: "The dollar ($) prefixed field '$inc' in 'query.$inc' is not valid for storage."

#7

* remove appneta script, tracelytics-java-agent and tracelyzer settings ...

from travis setup

#7

* remove require

was only needed for local testing

#7

* fix delayed job migration

the template is using erb and needs to be loaded with ERB and bindings
implemented by following the strategy from the gems spec/helper.rb
https://github.com/collectiveidea/delayed_job_active_record/blob/master/spec/helper.rb

#7

* adapt moped test continues, remove '{query:' from assertion as well

#7

* update xtrace tests for version 2 and small fix to is_valid?

#7

* one more fix of xtrace tests

#7

* fix BunnyClientTests: pin version, switch expectations

something changed in the bunny gem version 2.6.5 and our errors are not recognized as previously

#7

* fix mistake in bunny version (< 2.6.5 not 5.6.5)

#7

* exclude the combination of Ruby 2.4 and Rails 3.2 from the tests

- These versions are officially incompatible
- Rails 3.2 is not supported anymore

#7

* pin curb gem at version <= 9.3, because 9.4 breaks 2 tests

probably this commit: https://github.com/taf2/curb/commit/32fa6d78968c3b63e2a54a2c326efb577db04043

#7

* pin curb version, try different syntax

- because the previous approach didn't work in travis

#7

* oops, 0.9.3 not 9.3 for curb gem version

#7

* work-around to inconsistent sidekiq tests

account for the fact that the mbercount of redis events can vary and be either 2 or 4

#7

* get the right count, subtract redis_traces to get a consistent number

#7